export * from './tabs.component'
export * from './tabs.interface'
export * from './v2/tabs.component'
export * from './v2/tabs.interface'
export * from './v3/tabs.component'
export * from './v3/tabs.interface'
