import { theme } from "../..";

export type iIconTypes =
  | "amex"
  | "app"
  | "arrowRigth"
  | "bag"
  | "bankSlip"
  | "bell"
  | "block"
  | "brench1"
  | "brench2"
  | "calendar"
  | "camera"
  | "cardInfos"
  | "cashCircle"
  | "cashSign"
  | "cashSign2"
  | "check"
  | "chevronDown"
  | "chevronLeft"
  | "chevronRight"
  | "chevronUp"
  | "clipboard"
  | "clipboardText"
  | "clock"
  | "close"
  | "close2"
  | "coins2"
  | "commission"
  | "creditCard"
  | "defaut"
  | "diners"
  | "discover"
  | "download"
  | "drag"
  | "elo"
  | "envelope"
  | "eye"
  | "eyeSlash"
  | "facebook"
  | "faceCash"
  | "file"
  | "file1"
  | "file2"
  | "fileQuestion"
  | "filePlus"
  | "globe"
  | "grid"
  | "hamburguer"
  | "heart"
  | "helpCircle"
  | "hipercard"
  | "home"
  | "image"
  | "information"
  | "informationTriangle"
  | "instagram"
  | "instagramColor"
  | "link"
  | "linkedin"
  | "list"
  | "loading"
  | "lock"
  | "login"
  | "mastercard"
  | "messenger"
  | "minus"
  | "moreHorizontal"
  | "moreVertical"
  | "pen"
  | "percent"
  | "phone"
  | "pinLocation"
  | "play"
  | "playRounded"
  | "plus"
  | "receiptCheck"
  | "search"
  | "settings"
  | "share"
  | "shareOutline"
  | "shield"
  | "starEmpty"
  | "starFilled"
  | "tag"
  | "target4"
  | "ticket2"
  | "tiktok"
  | "trash"
  | "truck"
  | "twitter"
  | "user1"
  | "user2"
  | "users"
  | "visa"
  | "whatsapp"
  | "youtube"
  | "zapFast";

export type iIconSizes = "XXXS" | "XXS" | "XS" | "SM" | "MD" | "LG" | "XL";

export interface iIcon {
  iconId?: iIconTypes;
  OnColor?: boolean;
  onClick?: () => void;
  size?: iIconSizes;
  fill?: keyof typeof theme.colors & string;
  stroke?: keyof typeof theme.colors; // Main
  strokeWidth?: number;
  fluid?: boolean;
  width?: string;
  height?: string;
  gray?: boolean;
}
